"""empty message

Revision ID: 46b3be5110fa
Revises: 
Create Date: 2022-11-21 22:15:39.957828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b3be5110fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_VIA',
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('datahora', sa.DateTime(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('fluidez', sa.String(), nullable=True),
    sa.Column('ambulancia', sa.Boolean(), nullable=True),
    sa.Column('bombeiro', sa.Boolean(), nullable=True),
    sa.Column('policia', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cep')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TB_VIA')
    # ### end Alembic commands ###
